### ISSUE TITLE
Transaction to Paper-Wallet Address do not get confirmed

### ISSUE THREAD

**Issue by cucub** [maccaspacca/Bismuth-Paper-Wallet#1]
Hi,
Tested for a while but did not get any of the transactions to the Paper-Wallet address confirmed....

http://bismuth.online/ledgerquery => Error !!! Nothing found for the address or block hash you entered

Maybe I miss an important step....

**Comment by maccaspacca** [comment]
I have tested in test environment and in production. The generated wallet addresses accept transactions receive and send without issue.

**Comment by hclivess** [comment]
The address does not get recorded when it is created, but when it first receives a transaction. If I understand correctly, this is just the wording issue from https://github.com/maccaspacca/BismuthToolsWeb/issues/8

**Comment by maccaspacca** [comment]
Yes - I have updated he wording
https://github.com/maccaspacca/BismuthToolsWeb/issues/8
